### ISSUE TITLE
How does ChaiLove interact with the audio and video buffers?

### ISSUE THREAD

**Issue by tinglar** [libretro/libretro-chailove#293]
The way Libretro works is that you render audio and video into buffers, which are then put into callbacks that Libretro uses. In the cause of audio, you either render the samples or batches thereof (which skips the buffer, actually) and put those in the audio callback. In the case of video, you render into a framebuffer (a 2D array in which each cell represents a pixel) and put that in the video callback.

How does ChaiLove work with those audio and video buffers? Because I want to write my own Libretro core, I would like detailed explanations, please. I have a rather thorough knowledge of C, including pointers.

**Comment by RobLoach** [comment]
ChaiLove currently uses...

- Video: https://github.com/libretro/sdl-libretro/
- Audio: https://github.com/libretro/libretro-common/tree/master/audio

They manage the buffers. Pretty much looks something like this...
```
   // Set the frame buffer.
   video_cb(frame_buffer, SCREEN_WIDTH, SCREEN_HEIGHT, SCREEN_PITCH);
```

You can see https://github.com/robloach/libretro-cairo as a place where I was experimenting with Cairo for video.
