### ISSUE TITLE
Add alternative way to build chailove

### ISSUE THREAD

**Issue by jet082** [libretro/libretro-chailove#379]
Currently, chailove's makefile relies on checking out the latest versions of various libraries. I am trying to get chailove to work with iOS, but it is almost impossible to manage this with the make command constantly overwriting my work.

**Comment by jet082** [comment]
Nevermind, I'll just comment out the clean stuff currently.

**Comment by RobLoach** [comment]
Would be awesome to add it in a way that didn't need you to comment it out!

**Comment by RobLoach** [comment]
I removed the git submodule manipulation in the Makefile :+1: ... You're right, it was annoying.
