### ISSUE TITLE
Curious about possibility of MariO (Super Mario Bros/Portal Crossover) working:)

### ISSUE THREAD

**Issue by KMFDManic** [libretro/libretro-chailove#388]
@RobLoach Hope all is well with you, with this lockdown mess going on around the world!  I have been following your Updates with the Databases, etc.  You have simply been continuing to do an incredible job.  Out of curiosity, wonder what you make of this game, as far as working with ChaiLove, potentially?  Thanks for your input!

https://stabyourself.net/mari0/

Error Log from attempt to load:

[ChaiLove] ChaiLove 1.0.0
[ChaiLove] [filesystem] Mounting /media as /
[ChaiLove] [filesystem] Mounting /media/retroarch/cores as /libretro/core
[INFO] [Environ]: SYSTEM_DIRECTORY: "/media/retroarch/system".
[ChaiLove] [filesystem] Mounting /media/retroarch/system as /libretro/system
[INFO] [Environ]: CORE_ASSETS_DIRECTORY: "/media/retroarch/downloads".
[ChaiLove] [filesystem] Mounting /media/retroarch/downloads as /libretro/assets
[ChaiLove] [filesystem] Mounting /media/retroarch/saves as /libretro/saves
[ChaiLove] [script] Module conf not found.
[ChaiLove] [script] Module mari0_1/6/love not found.
[ChaiLove] [script] load() Cannot perform boxed_cast: St10shared_ptrIKN10chaiscript8dispatch19Proxy_Function_BaseEE to: St8functionIFvvEE
[ChaiLove] [script] reset() Error: "Can not find object: reset" 
[ChaiLove] [script] update(delta) Error: "Can not find object: update" 
[ChaiLove] [script] conf(t) Error: "Can not find object: conf" 
[ChaiLove] [script] joystickpressed() Error: "Can not find object: joystickpressed" 
[ChaiLove] [script] joystickreleased() Error: "Can not find object: joystickreleased" 
[ChaiLove] [script] mousepressed() Error: "Can not find object: mousepressed" 
[ChaiLove] [script] mousereleased() Error: "Can not find object: mousereleased" 
[ChaiLove] [script] mousemoved() Error: "Can not find object: mousemoved" 
[ChaiLove] [script] keypressed() Error: "Can not find object: keypressed" 
[ChaiLove] [script] keyreleased() Error: "Can not find object: keyreleased" 
[ChaiLove] [script] loadstate() Error: "Can not find object: loadstate" 
[ChaiLove] [script] savestate() Error: "Can not find object: savestate" 
[ChaiLove] [script] cheatreset() Warning: Error: "Can not find object: cheatreset" 
[ChaiLove] [script] cheatset() Warning: Error: "Can not find object: cheatset" 
[ChaiLove] [script] exit() Warning: Error: "Can not find object: exit" 
[ChaiLove] [script] Error loading /media/mari0_1.6.love
and then [ERROR] Failed to load content

**Comment by RobLoach** [comment]
Mari0 targets an old version of Love2D. ChaiLove just has support for ChaiScript instead of Lua. Could be possible to get it to work in libretro with Lutro though https://github.com/libretro/libretro-lutro

1. Update Lutro with new additions in Love2D https://github.com/libretro/libretro-lutro 
2. Update Mari0 to the new version of Love

Alternatively, would be interesting to add Lua support to ChaiScript. Hmmmmm

**Comment by RobLoach** [comment]
Going to close this. The best option would be to port to Lutro :wink:
