### ISSUE TITLE
Chailove core doesnt appear anymore listed for download

### ISSUE THREAD

**Issue by millansoft** [libretro/libretro-chailove#396]
From RetroArch 1.9.1 I noticed that Chailove core doesnt appear anymore listed for download, RetroArch 1.9.2 has the same problem.

**Comment by RobLoach** [comment]
Good catch. We will need to update to the new buildbot through gitlab CI. Need to update the gitlab workflow.

**Comment by Jaffacakelover** [comment]
Retroarch 1.9.5, issue persists - ChaiLove not appearing in Core Downloader or Load Core. Also not showing up in cores package from Buildbot.
