### ISSUE TITLE
Netplay

### ISSUE THREAD

**Issue by houbilami** [libretro/libretro-chailove#423]
Hi,
Thanks for this very nice framework!
Is this core compatible with netplay?
From libretro's doc I understand that it should, since save states are supported and netplay is checked in chailove's features list (https://docs.libretro.com/library/chailove).
But when I try to start hosting a game (for instance Floppy Bird), retroarch says "Core does not support netplay".
Is it because the game itself is not compatible or (as the error message suggests) because the chailove core is not compatible?
I am running retroarch 1.14.0 on linux x86-64.
Thanks

**Comment by RobLoach** [comment]
As long as the game implements the save states, and saves relevent information, then yes. It can be janky though, since the random number seed isn't kept persistent.
