### ISSUE TITLE
physfs-libretro: Push upstream to physfs

### ISSUE THREAD

**Issue by RobLoach** [libretro/libretro-chailove#429]
@phcoder What are your thoughts on pushing the [physfs-libretro bridge](https://github.com/libretro/libretro-chailove/blob/master/src/physfs_platform_libretro.c) upstream to [PhysFS](https://github.com/icculus/physfs) itself?

Looks like Ryan has been making a few more ports for SDL3 and playdate. Curious if he'd be okay with a libretro bridge in the upstream itself:
https://github.com/icculus/physfs

**Comment by phcoder** [comment]
I'm fine with upstreaming. Feel free to do it. This being said I'm very short on free time, so don't expect significant involvement from me

**Comment by RobLoach** [comment]
No worries! Thanks so much for putting it together.

**Comment by RobLoach** [comment]
The PR is up ^^
