### ISSUE TITLE
Lua support

### ISSUE THREAD

**Issue by RobLoach** [libretro/libretro-chailove#74]
https://github.com/ThePhD/sol2

**Comment by Ferk** [comment]
From the blog post and the intent to keep the "love" namespace it appears that the intention is to be compatible with the Löve API and that lua support would be Löve-compatible.

However, its not clear to me to which extent is this the intention, it seems to me that the API is love inspired but not really fully compliant. There are also things that wouldn't be directly translatable from lua to chaiscript, like how some love functions might return more than one return value simultaneously, which is something that Lua allows but chaiscript does not, for what I've seen.

Also, is it the intent that chailove should eventually replace lutro? It seems both projects kinda conflict in scope, specially if chailove eventually could run love games.

**Comment by RobLoach** [comment]
This issue was mostly out of curiosity. Since the scripting language is so detacted from the rest of the system in ChaiLove, it is possible that we could support both ChaiScript and Lua. Detect if there's a main.chai or a main.lua, and load it accordingly. In the PR, I had troubles compiling Lua correctly.

> Also, is it the intent that chailove should eventually replace lutro?

Some of the goals between the two projects differ. Lutro, for example, aims to be as minimalistic as possible (implements its own graphics engine, etc), while ChaiLove brings in SDL to ease the development process.

ChaiLove doesn't mean to replace Lutro, but add to the game development ecosystem within libretro.

> seems both projects kinda conflict, specially if chailove eventually could run love games.

Would be pretty great if ChaiLove could run Love games. That's a far way off, but would be a neat achievement. Lutro is a ways from that too, but who knows!

**Comment by RobLoach** [comment]
Going to re-open this one, as it's not too crazy an idea... https://github.com/ThePhD/sol2

**Comment by RobLoach** [comment]
Duplicate of https://github.com/libretro/libretro-chailove/issues/340
